apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-running
  labels:
    lab: pod-lifecycle
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "while true; do echo running; sleep 30; done"]
