apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-replicaset
  template:
    metadata:
      labels:
        app: demo-replicaset
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
