apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-recreate
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app-recreate
  template:
    metadata:
      labels:
        app: app-recreate
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          command: ["sh", "-c", "echo 'Application v2' > /usr/share/nginx/html/index.html; exec nginx -g 'daemon off;'"]
          ports:
            - containerPort: 80
