apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strategy-app
      slot: green
  template:
    metadata:
      labels:
        app: strategy-app
        slot: green
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          command: ["sh", "-c", "echo 'GREEN v2' > /usr/share/nginx/html/index.html; exec nginx -g 'daemon off;'"]
          ports:
            - containerPort: 80
