apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-liveness
  labels:
    lab: pod-lifecycle
spec:
  containers:
    - name: app
      image: nginx:1.27-alpine
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
