apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-startup
  labels:
    lab: pod-lifecycle
spec:
  containers:
    - name: app
      image: nginx:1.27-alpine
      command: ["sh", "-c", "sleep 10; exec nginx -g 'daemon off;'"]
      startupProbe:
        tcpSocket:
          port: 80
        failureThreshold: 10
        periodSeconds: 2
