---
# Source: notes/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-config
data:
  GREETING: "DevOps Notes"
  ENVIRONMENT: "classroom"
  APP_VERSION: "1.0"

---
# Source: notes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: notes
spec:
  selector:
    app: notes
  ports:
    - name: http
      port: 5000
      targetPort: http

---
# Source: notes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
      annotations:
        checksum/config: 779ac4024b8ba64d2149a1c023ac9648f4c518becf4a7168a64afad96d9546bf
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      containers:
        - name: notes
          image: "devsecops:1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: notes-config
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: API_TOKEN
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: temporary
              mountPath: /tmp
      volumes:
        - name: temporary
          emptyDir: {}
