apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-app
      track: canary
  template:
    metadata:
      labels:
        app: canary-app
        track: canary
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          command: ["sh", "-c", "echo 'CANARY v2' > /usr/share/nginx/html/index.html; exec nginx -g 'daemon off;'"]
          ports:
            - containerPort: 80
